version: "3"
services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=devpassword
    networks:
      - letsgo-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "devpassword"]
    ports:
      - "6379:6379"
    networks:
      - letsgo-network
    restart: unless-stopped

networks:
  letsgo-network:
    driver: bridge
