
// protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. proto/matching/matching.proto

// Protocol Buffers Syntax

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: matching/matching.proto

// Package Name

package matching

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Matcher_MatchUser_FullMethodName = "/matching.Matcher/MatchUser"
)

// MatcherClient is the client API for Matcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatcherClient interface {
	MatchUser(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
}

type matcherClient struct {
	cc grpc.ClientConnInterface
}

func NewMatcherClient(cc grpc.ClientConnInterface) MatcherClient {
	return &matcherClient{cc}
}

func (c *matcherClient) MatchUser(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, Matcher_MatchUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatcherServer is the server API for Matcher service.
// All implementations must embed UnimplementedMatcherServer
// for forward compatibility.
type MatcherServer interface {
	MatchUser(context.Context, *MatchRequest) (*MatchResponse, error)
	mustEmbedUnimplementedMatcherServer()
}

// UnimplementedMatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatcherServer struct{}

func (UnimplementedMatcherServer) MatchUser(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchUser not implemented")
}
func (UnimplementedMatcherServer) mustEmbedUnimplementedMatcherServer() {}
func (UnimplementedMatcherServer) testEmbeddedByValue()                 {}

// UnsafeMatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatcherServer will
// result in compilation errors.
type UnsafeMatcherServer interface {
	mustEmbedUnimplementedMatcherServer()
}

func RegisterMatcherServer(s grpc.ServiceRegistrar, srv MatcherServer) {
	// If the following call pancis, it indicates UnimplementedMatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Matcher_ServiceDesc, srv)
}

func _Matcher_MatchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServer).MatchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matcher_MatchUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServer).MatchUser(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Matcher_ServiceDesc is the grpc.ServiceDesc for Matcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.Matcher",
	HandlerType: (*MatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MatchUser",
			Handler:    _Matcher_MatchUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching/matching.proto",
}
