// protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. proto/matching/matching.proto

// Protocol Buffers Syntax
syntax = "proto3";

// Package Name
package matching;

option go_package = "./;matching";
 
service Matcher {
  rpc MatchUser (MatchRequest) returns (MatchResponse);
}

message MatchRequest {
  int32 user_id = 1;
  string module = 2; // e.g., "chat", "call", "video"
  repeated string tags = 3; // e.g., ["gaming", "bike"]
}

message MatchResponse {
  bool matched = 1;
  int32 partner_id = 2;
}
