version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: matching-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - redis_data:/data1

  matching-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matching-service
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - GRPC_PORT=${GRPC_PORT}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"

volumes:
  redis_data:
